apiVersion: v1
kind: Namespace
metadata:
  name: plataforma-comm-dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plataformacomm-front-config
  namespace: plataforma-comm-dev
data:
  NEXT_PUBLIC_APP_ENV: "dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plataformacomm-front
  namespace: plataforma-comm-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: plataformacomm-front
  template:
    metadata:
      labels:
        app: plataformacomm-front
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: plataformacomm-front
          image: <SEU_REGISTRY>/plataformacomm-front:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: plataformacomm-front-config
                  key: NEXT_PUBLIC_APP_ENV
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      terminationGracePeriodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: plataformacomm-front
  namespace: plataforma-comm-dev
spec:
  type: ClusterIP
  selector:
    app: plataformacomm-front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plataformacomm-front
  namespace: plataforma-comm-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-internal
  rules:
    - host: plataformacomm.dev.ia.btgpactual.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plataformacomm-front
                port:
                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: plataformacomm-front
  namespace: plataforma-comm-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plataformacomm-front
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
