export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Providers } from "./providers";
import "../styles/fonts.css";
import { LanguageProvider } from "@/lib/language-selector/LanguageProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="pt-br">
      <body
      	style={{
					boxSizing: "content-box",
					width: "100%",
					maxWidth: "100%",
					backgroundColor: "#F5F5F6",
					scrollbarColor: "blue",
					fontFamily: "BTGPactualSans"
				}}
      >
        <LanguageProvider>
          <Providers>
            {children}
          </Providers>
        </LanguageProvider>
      </body>
    </html>
  )
}
